ref/general/hello-world-appsody-codewind.adoc, ref/general/hello-world-kabanero.adoc, ref/general/kabanero-foundation-setup.adoc, ref/general/tektonUI-webhook.adoc
-Adds some front matter to docs to help Jekyll process them on the front-end.  
-Renames the Kabanero getting started doc filename
=> Doc update

ref/scripts/appsody-tekton-example-manual-run.sh, ref/scripts/install-kabanero-foundation.sh
- Pipeline components are now installed as part of Collections, trim example run accordingly
- Update install using release 0.0.2 artifacts
https://github.com/kabanero-io/roadmap/issues/46
=> updates for release 0.0.2

ref/general/collection-management.adoc
Publish initial collection documentation.
=> collections.adoc

ref/general/scripted-kabanero-foundation-setup.adoc
scripted install & example adoc that pairs with 0.0.2 release
=> script adoc

ref/general/collection-management.adoc
Change "default" to "featured" collections.
=> nate comments

ref/general/codewind-kabanero-collections.adoc, ref/general/hello-world-appsody-codewind.adoc
For 
https://github.com/kabanero-io/kabanero-collection/issues/25
https://github.com/kabanero-io/roadmap/issues/61
https://github.com/kabanero-io/kabanero-collection/issues/15
=> Add docs for using Kabanero Collections on Codewind

installing developer tools
Here is "installing developer tools" including instructions for "installing Codewind for VS Code" and " installing Codewind for Eclipse"
=> Create installing developer tools

README.md, doc-categories.adoc
create a custom order that the docs will show in our table of contents for the stie
=> add doc categories

ref/general/installing-kabanero-foundation.adoc
Tell the user to review the script for optional components that they may wish to enable.  There will be more and it's probably not appropriate to list them all on this page.
=> Add information about optional components in the install script.

ref/general/kabenero-cli.adoc
part of kabanero-io/kabanero-command-line/issues/94
=> format and enhance cli doc

ref/general/tekton-webhooks.adoc
closes kabanero-io/docs/issues/133
=> edit service account

doc-categories.adoc
=> Add new "Overview" category to docs

ref/general/installing-kabanero-foundation.adoc
This is the documentation for kabanero-io/kabanero-foundation#88.  Documenting how to use the upgrade script to change releases of Kabanero.
=> Add upgrade information

ref/general/kabanero-cli.adoc
closes https://github.com/kabanero-io/kabanero-command-line/issues/3
=> adding example results to cli ref doc

README.md
- Add render your guide section
- Add image format for markdown
=> Update dev instructions for Doc pages

README.md
- also add new category "Overview"
=> Update markdown frontmatter instructions for Docs

ref/general/kabanero-env-vars.md
- new reference topic for env vars used to configure collection build.
Closes: #187
=> Add topic for Environment variable

ref/general/app-deploy-namespace.adoc
- some small restructuring and re-wording for clarity
=> Editorial review of content

ref/general/codewind-kabanero-collections.adoc, ref/general/installing-dev-tools.adoc
The existing topic https://kabanero.io/docs/ref/general/codewind-kabanero-collections.html
contains inaccuracies. Eventually this topic will be replaced by a guide, but
in the short term this topic is updated for technical accuracy.
Installing Codewind topic also updated to improve navigation between VS Code
and Eclipse, and provide links to the updated "Working with Collections in
VS Code or Eclipse".
Closes: #196
=> Improve Codewind install and using topics

ref/general/collection-install.adoc, ref/general/github-authorization.adoc, ref/general/kabanero-cli.adoc
=> break github authorization out into new page

ref/general/github-createteam.adoc
=> create new page for git team creation

ref/general/configuration/tekton-webhooks.adoc
=> fixing broken links, were pointing to a git branch instead of master

ref/general/reference/kabanero-cli.adoc
=> add brew install

ref/general/reference/kabanero-cli.adoc
In 0.4.0 the CLI has changed to take in the password at login in stdin instead of in plaintext
=> CLI 0.4.0 login doc change

ref/general/reference/troubleshooting.adoc
=> adding webhook creation issue to troubleshooting

ref/general/configuration/console-oauth.adoc, ref/general/installation/installing-kabanero-foundation.adoc
part of kabanero-io/kabanero-landing/issues/92
=> add doc for configuring oauth for the console

ref/general/configuration/collection-install.adoc, ref/general/configuration/github-authorization.adoc, ref/general/installation/installing-kabanero-foundation.adoc, ref/general/installation/uninstalling-kabanero-foundation.adoc
=> Update docs for version change

ref/general/whats-new.md
=> first draft whats new page for 0.5.0

ref/general/configuration/rhsso.adoc
need to change secret names so they match the code in the operator
=> correct secret keynames

ref/general/configuration/app-deploy-namespace.adoc
This is #287 for Kabanero 0.4.x
=> multiple namespace instructions updates kabanero 0.4

ref/general/configuration/tekton-webhooks.adoc
=> removing hostpath pv example, updating link to pipelines guide instead

ref/general/reference/kabanero-cli.adoc
=> formatting and message updates

ref/general/whats-new.md
=> Update whats-new for 060

ref/general/installation/installing-dev-tools.adoc, ref/general/installation/installing-kabanero-foundation.adoc, ref/general/installation/uninstalling-kabanero-foundation.adoc
=> updates to install docs for v0.6

ref/general/configuration/kabanero-cr-config.adoc, ref/general/configuration/rhsso.adoc, ref/general/configuration/stack-cr-config.adoc, ref/general/configuration/stack-install.adoc, ref/general/configuration/tekton-webhooks.adoc
=> review edits and more terminology

ref/general/configuration/kabanero-cr-config.adoc, ref/general/configuration/stack-cr-config.adoc
=> Tweak language for clarity

ref/general/reference/kabanero-cli.adoc
=> Tweaks to correct CLI doc

ref/general/configuration/app-deploy-namespace.adoc, ref/general/configuration/kabanero-cr-config.adoc, ref/general/configuration/stack-cr-config.adoc, ref/general/configuration/stack-install.adoc, ref/general/configuration/tekton-webhooks.adoc, ref/general/installation/installing-codeready-and-codewind.adoc, ref/general/installation/installing-dev-tools.adoc, ref/general/installation/uninstalling-kabanero-foundation.adoc, ref/general/reference/kabanero-cli.adoc, ref/general/reference/troubleshooting.adoc
=> backporting terminology changes

ref/general/configuration/github-authorization.adoc, ref/general/configuration/kabanero-cr-config.adoc, ref/general/configuration/stack-cr-config.adoc, ref/general/configuration/stack-install.adoc, ref/general/configuration/tekton-webhooks.adoc, ref/general/installation/installing-codeready-and-codewind.adoc, ref/general/reference/kabanero-cli.adoc
closes https://github.com/kabanero-io/docs/issues/358
=> minor additional terminology, sync and other edits

ref/general/installation/installing-codeready-and-codewind.adoc
Signed-off-by: Jacob Berger <jacob.berger@ibm.com>
For #362 
@alohr51, I'm not sure who would review and then merge this PR, so I'm tagging you.
=> fixed  broken link

ref/general/configuration/kabanero-cr-config.adoc, ref/general/configuration/stack-governance.adoc
There is not enough information here, but I am hoping we can use this as a start to document the stack governance.  I am hoping to convey here:
* What stack governance is
* What the policies are
* How to create a `Secret` to use to obtain the digest from the container registry
Please blast away with comments :-)
=> WIP - Start a stack governance page

ref/general/reference/kabanero-cli.adoc
Also includes what all the possible outputs are for the digest column
=> Adds digest check column to list

ref/general/configuration/ghe-credentials.adoc, ref/general/configuration/kabanero-cr-config.adoc, ref/general/installation/installing-kabanero-foundation.adoc, ref/general/reference/kabanero-cli.adoc
=> GSR to update 0.7 to 0.8 in docs

ref/general/reference/kabanero-cli.adoc
Reference doc for creating Kube secret for container registries
=> Reference doc for creating Kube secret for container registries

ref/general/configuration/ghe-credentials.adoc, ref/general/configuration/github-authorization.adoc, ref/general/configuration/stack-governance.adoc
=> fixing links, and minor text edits

ref/general/configuration/ghe-credentials.adoc, ref/general/configuration/kabanero-cr-config.adoc, ref/general/installation/installing-codeready-and-codewind.adoc, ref/general/installation/installing-kabanero-foundation.adoc, ref/general/installation/uninstalling-kabanero-foundation.adoc, ref/general/reference/kabanero-cli.adoc
@kaczyns please double-check URL changes (e.g., in kabanero-cr-config)
=> 0.8 to 0.9, also updating a couple of URLs

ref/general/installation/installing-codeready-and-codewind.adoc, ref/general/installation/installing-dev-tools.adoc
Codewind website updated and changed their links. Fixing broken links
in these  topics.
=> Fix broken links

ref/general/installation/installing-codeready-and-codewind.adoc
=> add instruction on how to edit Kab CR

ref/general/reference/kabanero-cli.adoc
=> changes to login for TLS cert

ref/general/installation/installing-kabanero-foundation.adoc
=> change post-install instructions

ref/general/configuration/tekton-webhooks.adoc
=> updates to webhooks page, alerting events operator
