kabanero-io/docs

- ref/general/codewind-kabanero-collections.adoc
- ref/general/collection-building.adoc
- ref/general/collection-management.adoc
- ref/general/docs-welcome.adoc
- ref/general/hello-world-appsody-codewind.adoc
- ref/general/installing-dev-tools.adoc
- ref/general/installing-kabanero-foundation.adoc
- ref/general/kabenero-cli.adoc
- ref/general/tekton-webhooks.adoc
Doc changes to support the updated docs on the website (https://github.com/kabanero-io/kabanero-website/pull/201/files).  The layout for the docs is named `doc` and docs that want to implement clickable anchors should include `:sectanchors:`
> Use anchors and doc layout

- ref/general/installing-kabanero-foundation.adoc
The optional instruction at the end has
`tekton.dev/pipelineRun=appsody-manual-pipeline-run`
but the code itself changed the label to
`tekton.dev/pipelineRun=manual-pipeline-run`
> Label for pipeline run changed

- ref/general/installing-kabanero-foundation.adoc
- ref/general/whats-new.md
closes kabanero-io/kabanero-landing/issues/30
also update what's new meta data (it was outdated)
rendered doc looks like
> add how to view landing page in install doc

- ref/general/kabanero-cr-config.adoc
- ref/general/kabanero_cr_config.adoc
There are places in the doc where we refer to the Kabanero CR (or perhaps where we should), but we do not define what it is our how to set one up.  This page describes what can be configured in the Kabanero CR.  It's not a complete list, but covers what most users would be interested in.  I plan to come back with future PRs that link to this page in the appropriate places.
> Document the Kabanero CR so it can be linked to from other places.

- ref/general/kabanero-cli.adoc
I needed a specific OAuth scope when creating my GitHub PAT to let the cli access the data it needed to log me in
> clarify github PAT OAuth scope

- ref/general/installing-kabanero-foundation.adoc
- ref/general/uninstalling-kabanero-foundation.adoc
Fixes #177 
The install script has moved to the kabanero-operator repository, and is generated and attached to the release.  I've updated the install and uninstall pages to reference this.
> Update install instructions for 0.3.0

- ref/general/installing-kabanero-foundation.adoc
Fixes kabanero-io/kabanero-operator#64
I added a line to the install section about the authority required to create a `Kabanero` CR instance.  Specifically, it does not need to be a `cluster-admin` who creates this object.  A user might wish to leave this task to someone with a lower level of authority in the cluster.
> Add a blurb about the authority required to make a Kabanero CR instance

- ref/general/collection-install.adoc
Topic kabanero-cr-config.html appears in the reference section but is a task topic.
- moved the topic to the Configuring section
- removed the link to a topic already removed from the Docs
- change a link title to match the target
- minor edits to fix terms
Part of epic #176
> Move configuring topic to configuring section of Docs

- ref/general/installing-kabanero-foundation.adoc
- ref/general/uninstalling-kabanero-foundation.adoc
The Kabanero 0.3.0 install script won't work anymore on OCP 4.2, since the OpenShift Serverless operator was upgraded to v1.2.0 and is not compatible with the older v1.1.0.  This is fixed in Kabanero 0.3.1.  This PR updates the install instructions to reference the Kabanero 0.3.1 install and uninstall scripts.
> Replace 0.3.0 install script with 0.3.1 install script

- ref/general/kabanero-env-vars.md
Duplicate header in Docs caused by a #1 and the title: frontmatter.
Removed #1
> Remove duplicate header

- ref/general/configuration/tekton-webhooks.adoc
per guidance, remove reference to Kabanero Enterprise from the prereqs. Since this doc is on the Kabanero.io site, I assume we don't replace with ICP4Apps and instead just leave Kabanero Foundation as the only prereq on this bullet.
> remove reference to Kabanero Enterprise

- ref/general/whats-new.md
Reverts kabanero-io/docs#265
Blog post isn't ready, but we should get 0.5.0 docs out there.
> Revert "first draft whats new page for 0.5.0"

- ref/general/configuration/kabanero-cr-config.adoc
- ref/general/configuration/stack-cr-config.adoc
Fixes #272 
This contains most (if not all) of the updates to the Kabanero and Stack CR instances for Kabanero 0.6.0.  Additions include:
* Stack CR instance (new)
* CodeReady Workspaces configuration
* RH SSO configuration
Note that this is not complete documentation for either CodeReady or RH SSO - this is just documenting what can be configured in the Kabanero and Stack CR instances.
> Stack config doc

- ref/general/configuration/app-deploy-namespace.adoc
The OpenShift Serverless operator v1.1.0 requires applications to explicitly manage the service mesh member role (smmr).  If applications use Knative, they will need to perform this step.  Kabanero versions 0.3 and 0.4 use the Serverless operator v1.1.0.  This PR is for 0.3.  A separate PR will handle 0.4.
> multiple namespace instructions updates kabanero 0.3.x

- ref/general/configuration/kabanero-cr-config.adoc
- ref/general/installation/installing-codeready-and-codewind.adoc
First crack at the install documentation for CodeReady Workspaces + Codewind in the Kabanero operator. Covers the following: 
- Prerequisites for CodeReady Workspaces + Codewind
- Configuring the Kabanero CR instance to install CodeReady Workspace
- Optional: Configuring with TLS and OpenShift oAuth
- Creating a Codewind workspace
- Uninstalling Codewind and CodeReady
I've also updated the references of `Spec.codereadyWorkspaces` to `Spec.codeReadyWorkspaces`, as that's the proper value in the Kabanero CR.
@j-c-berger Please review
> CodeReady install docs

- ref/general/installation/installing-kabanero-foundation.adoc
- ref/general/reference/troubleshooting.adoc
* There is no more `Kabanero` tab on the OKD console.  We should not mention it.
* Point to the guides at the end of the "next steps" section to give the user an idea of what to do next.
* Explicitly call out that a 3x3 cluster is required
> Remove reference to the landing page tab in OCP console, etc

- ref/general/configuration/app-deploy-namespace.adoc
- ref/general/configuration/github-authorization.adoc
- ref/general/configuration/kabanero-cr-config.adoc
- ref/general/configuration/rhsso.adoc
- ref/general/configuration/stack-install.adoc
- ref/general/reference/troubleshooting.adoc
See openshift/console#4444.  We're trying to steer people away from using the OpenShift console when editing their Kabanero CR instances, due to its perceived tendency to prefer the v1alpha1 version of the Kabanero CRD.  
If anything, this PR should show where the places are in the Kabanero doc that need to be changed.  How we tell people to stop using the console is up for discussion.
@jantley-ibm @tam512
> WIP - Avoid using the OpenShift console for editing Kabanero CR

- ref/general/installation/installing-kabanero-foundation.adoc
There are several things wrong with the command to access the pipeline logs:
- the pipelineRun name does not match what was in the `example-tekton-pipeline-run.sh` script
- the namespace needs to be specified
- quotes need to surround the output option's value (at least for zsh users)
> Fix the pipeline logs command

- ref/general/configuration/console-oauth.adoc
we need people to know they must update the CRD with the GitHub spec before OAuth can work properly.
The CLI service authorization is technically a prerequisite.
> tell users to config cli before config Console OAuth 

- ref/general/configuration/ghe-credentials.adoc
- ref/general/configuration/kabanero-cr-config.adoc
- ref/general/configuration/stack-cr-config.adoc
- ref/general/configuration/stack-install.adoc
Users can now access stack hub indexes and pipeline zips that are protected by GitHub in a private repository, or by GHE.  This documentation explains how to configure the Kabanero CR instance to do that.
@mezarin would you please review this from a technical perspective?
This will also need an ID review.
> Add information for configuring GHE assets

- ref/general/configuration/stack-install.adoc
There was some (understandable) confusion within our system test team about what should happen when the stack index in the Kabanero CR instance is replaced.  The Kabanero operator does not currently delete stacks, or versions of stacks, which were removed from an index.  This will become the behavior in a future release (see kabanero-io/kabanero-operator#353).  The current behavior needs to be documented somewhere, and this PR attempts to address that.
@jgawor FYI (we spoke about this, this afternoon)
> Add note about stack index behavior

- ref/general/installation/installing-codeready-and-codewind.adoc
Signed-off-by: Jacob Berger <jacob.berger@ibm.com>
@SueChaplain or @jantley-ibm please review this change for the broken link in our `installing codeready and codewind` doc. This PR is made on the 0.7.0 branch. 
I made a similar PR, #363 for the 0.8.0 branch. 
Once this PR is approved and merged, I can ask Andrew to run another build and update the website. thanks!
> Fixed broken link for 0.7.0

- ref/general/configuration/stack-install.adoc
Resolves kabanero-io/kabanero-operator#353
We added a note in the `release-0.6` branch to reflect an odd behavior.  We've fixed the odd behavior in 0.7, and now we'd like to add a different note that makes it clear what the new (correct) behavior is.
> Update note to reflect desiredState

- ref/general/reference/troubleshooting.adoc
Fixes kabanero-io/kabanero-operator#610
If pieces of Knative Serving are left in the cluster when installing Kabanero, the Appsody operator may fail to start.  This will be fixed in Appsody operator 0.5.0, but since Kabanero 0.8.0 uses Appsody 0.4.0, we need to document the work-around.
> bypass for appsody 0.4.0 / knative serving bug

- ref/general/configuration/kabanero-cr-config.adoc
- ref/general/configuration/stack-cr-config.adoc
For 0.8.0, the Kabanero CR instance contains a new spec.stacks.skipRegistryCertVerification entry that needs to be documented.
> Add new Kabanero Operator CR spec entry.

- ref/general/configuration/kabanero-cr-config.adoc
This is not attempting to be a complete documentation of `Gitops`.  It's just documenting the new configuration pieces in the Kabanero CR instance.
> Add gitops configuration to the Kabanero CR instance

- ref/general/reference/kabanero-cli.adoc
Onboard is no longer a command in 0.9.0
https://github.com/kabanero-io/kabanero-command-line/pull/235
> Removes Onboard from kab-doc

- ref/general/configuration/github-authorization.adoc
- fix list
- remove the '+', which appear in clear text.
Tested and good.
> Fix formatting of adoc
